"""Database creation

Revision ID: ed42df8374c2
Revises: 043c365b95b2
Create Date: 2023-04-08 08:21:09.696201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed42df8374c2'
down_revision = '043c365b95b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
